version: '2'
services:
  complexjhipsterapplication-app:
    image: complexjhipsterapplication
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
      - SPRING_DATA_MONGODB_URI=mongodb://complexjhipsterapplication-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=ComplexJHipsterApplication
      - JHIPSTER_CACHE_REDIS_SERVER=redis://complexjhipsterapplication-redis:6379
      - JHIPSTER_CACHE_REDIS_CLUSTER=false
      # - JHIPSTER_CACHE_REDIS_SERVER=redis://complexjhipsterapplication-redis:6379
      # - JHIPSTER_CACHE_REDIS_CLUSTER=true
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=http://keycloak:9080/auth/realms/jhipster
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=web_app
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=web_app
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://complexjhipsterapplication-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://complexjhipsterapplication-elasticsearch:9200
    ports:
      - 8080:8080
  complexjhipsterapplication-mongodb:
    extends:
      file: mongodb.yml
      service: complexjhipsterapplication-mongodb
  complexjhipsterapplication-redis:
    extends:
      file: redis.yml
      service: complexjhipsterapplication-redis
  complexjhipsterapplication-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: complexjhipsterapplication-elasticsearch
  jhipster-registry:
    extends:
      file: jhipster-registry.yml
      service: jhipster-registry
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=native
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS=file:./central-config/docker-config/
  keycloak:
    extends:
      file: keycloak.yml
      service: keycloak
